# -*- coding: utf-8 -*-
"""Test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CNd8CkV0D9_eiWdr2j_f3i5qoWBq3AzN
"""

import os
import json
import math
from dataclasses import dataclass, asdict
from datetime import datetime
# --- FIX: IMPORT TUPLE, LIST, DICT, ANY, OPTIONAL ---
from typing import List, Dict, Any, Optional, Tuple 
# --- END FIX ---

import torch
import cv2
import whisper
import pytesseract

# ---------------------------------------------------------
# Data models
# ---------------------------------------------------------

@dataclass
class AudioSegment:
    segment_id: str
    index: int
    start_sec: float
    end_sec: float
    text: str
    confidence: float
    speaker: Optional[str] = None
    metadata: Dict[str, Any] = None


@dataclass
class VisualKeyframe:
    frame_id: str
    time_sec: float
    image_path: str
    kind: str          # "slide", "instructor", "other", "unknown"
    caption: str
    ocr_text: str
    tags: List[str]
    metadata: Dict[str, Any] = None


# ---------------------------------------------------------
# Helpers
# ---------------------------------------------------------

def generate_id(prefix: str, index: int, width: int = 4) -> str:
    return f"{prefix}_{index:0{width}d}"


def now_iso() -> str:
    return datetime.utcnow().isoformat(timespec="seconds") + "Z"


# ---------------------------------------------------------
# 1) Transcribe MP4 directly with Whisper (local, no API)
# ---------------------------------------------------------

def transcribe_video_local(
    video_path: str,
    model_name: str = "base",
    language: Optional[str] = None
) -> List[AudioSegment]:
    """
    Uses local Whisper to transcribe the full MP4 with timestamps.
    Returns a list of AudioSegment.
    """
    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"[decoder] Loading Whisper model '{model_name}' on {device}...")
    model = whisper.load_model(model_name, device=device)

    print(f"[decoder] Transcribing video: {video_path}")
    # Whisper can take MP4 directly – ffmpeg handles the audio extraction
    result = model.transcribe(
        video_path,
        language=language,
        verbose=True
    )

    segments_list = result.get("segments", [])
    audio_segments: List[AudioSegment] = []

    for i, seg in enumerate(segments_list):
        seg_id = generate_id("seg", i + 1)
        # Convert log probability to confidence score (0-1 range)
        raw_logprob = float(seg.get("avg_logprob", 0.0))
        # Whisper returns avg_logprob (typically negative), convert to probability
        # Using exp() to convert log probability to probability
        confidence = min(1.0, max(0.0, math.exp(raw_logprob)))
        
        audio_segments.append(
            AudioSegment(
                segment_id=seg_id,
                index=i,
                start_sec=float(seg["start"]),
                end_sec=float(seg["end"]),
                text=seg["text"].strip(),
                confidence=confidence,
                speaker=None,
                metadata={"raw_logprob": raw_logprob}
            )
        )

    print(f"[decoder] Transcription produced {len(audio_segments)} segments")
    return audio_segments


# ---------------------------------------------------------
# 2) Frame sampling + OCR with Tesseract
# ---------------------------------------------------------

def ocr_frame_text(
    frame_bgr,
    lang: str = "eng"
) -> str:
    """
    Run Tesseract OCR on a single frame (numpy array BGR from OpenCV).
    Basic pre-processing: convert to RGB and optionally grayscale.
    """
    # Convert BGR (OpenCV) -> RGB (pytesseract expects RGB)
    frame_rgb = cv2.cvtColor(frame_bgr, cv2.COLOR_BGR2RGB)

    # Optional: convert to grayscale + threshold for cleaner text on slides
    gray = cv2.cvtColor(frame_rgb, cv2.COLOR_RGB2GRAY)
    # Simple binary threshold; you can tune this for your videos
    _, thresh = cv2.threshold(gray, 180, 255, cv2.THRESH_BINARY)

    # Run OCR
    text = pytesseract.image_to_string(thresh, lang=lang)
    return text.strip()


def extract_keyframes_fixed_interval(
    video_path: str,
    output_dir: str,
    interval_sec: float = 10.0,
    ocr_lang: str = "eng"
# --- FIX: CHANGED RETURN TYPE SYNTAX ---
) -> Tuple[List[VisualKeyframe], float, float, int, int]:
# --- END FIX ---
    """
    Sample frames every `interval_sec` seconds and save as PNG files.
    Also run OCR on each frame and store the text.
    Returns:
      - list of VisualKeyframe
      - duration_sec
      - fps
      - width
      - height
    """
    os.makedirs(output_dir, exist_ok=True)

    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        raise RuntimeError(f"Could not open video: {video_path}")

    fps = cap.get(cv2.CAP_PROP_FPS)
    total_frames = cap.get(cv2.CAP_PROP_FRAME_COUNT)
    duration_sec = total_frames / fps if fps > 0 else 0.0

    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

    keyframes: List[VisualKeyframe] = []
    current_time = 0.0
    frame_index = 0
    prev_ocr_text = ""  # Track previous OCR for deduplication

    print(f"[decoder] Sampling frames every {interval_sec} seconds...")
    print(f"[decoder] Video duration ~{duration_sec:.1f}s, FPS={fps:.1f}")

    while current_time <= duration_sec:
        cap.set(cv2.CAP_PROP_POS_MSEC, current_time * 1000)
        success, frame = cap.read()
        if not success:
            break

        frame_id = generate_id("frame", frame_index + 1)
        filename = f"{frame_id}.png"
        image_path = os.path.join(output_dir, filename)

        cv2.imwrite(image_path, frame)

        # OCR
        try:
            ocr_text = ocr_frame_text(frame, lang=ocr_lang)
        except Exception as e:
            print(f"[decoder][WARN] OCR failed on {frame_id}: {e}")
            ocr_text = ""

        # Deduplicate OCR: if very similar to previous frame, mark as duplicate
        is_duplicate = False
        if ocr_text and prev_ocr_text:
            # Calculate similarity (simple approach: exact match or very close)
            similarity = len(set(ocr_text.split()) & set(prev_ocr_text.split())) / max(len(ocr_text.split()), len(prev_ocr_text.split()))
            if similarity > 0.9:  # 90% similarity threshold
                is_duplicate = True
                ocr_text = f"[DUPLICATE_OF_PREVIOUS] {ocr_text[:50]}..." if len(ocr_text) > 50 else f"[DUPLICATE_OF_PREVIOUS] {ocr_text}"
        
        if not is_duplicate and ocr_text:
            prev_ocr_text = ocr_text

        # Classify frames as slides based on OCR content
        # If OCR detected substantial text, it's likely a slide
        if ocr_text and len(ocr_text.strip()) > 20 and not is_duplicate:
            kind = "slide"
        else:
            kind = "unknown"
        
        caption = ""    # could later be generated from OCR/LLM
        tags: List[str] = []

        keyframes.append(
            VisualKeyframe(
                frame_id=frame_id,
                time_sec=float(current_time),
                image_path=os.path.abspath(image_path),
                kind=kind,
                caption=caption,
                ocr_text=ocr_text,
                tags=tags,
                metadata={}
            )
        )

        frame_index += 1
        current_time += interval_sec

    cap.release()

    print(f"[decoder] Sampled {len(keyframes)} frames")
    return keyframes, duration_sec, fps, width, height


# ---------------------------------------------------------
# 3) Simple alignment audio ↔ visual
# ---------------------------------------------------------

def find_nearest_frame(
    target_time: float,
    visual_frames: List[VisualKeyframe]
) -> Optional[str]:
    """
    Find the frame_id of the keyframe closest to target_time.
    Returns None if no frames available.
    """
    if not visual_frames:
        return None
    
    nearest_frame = min(visual_frames, key=lambda f: abs(f.time_sec - target_time))
    return nearest_frame.frame_id


def validate_alignment(
    alignments: List[Dict[str, Any]],
    audio_segments: List[AudioSegment],
    visual_frames: List[VisualKeyframe],
    max_time_diff: float = 15.0
) -> Dict[str, Any]:
    """
    Validate that audio-visual alignments make temporal sense.
    Returns a report with any suspicious alignments.
    """
    issues = []
    frame_lookup = {f.frame_id: f for f in visual_frames}
    segment_lookup = {s.segment_id: s for s in audio_segments}
    
    for alignment in alignments:
        segment_id = alignment["segment_id"]
        frame_ids = alignment["frame_ids"]
        
        if segment_id not in segment_lookup:
            continue
            
        segment = segment_lookup[segment_id]
        segment_mid = (segment.start_sec + segment.end_sec) / 2
        
        for frame_id in frame_ids:
            if frame_id not in frame_lookup:
                continue
                
            frame = frame_lookup[frame_id]
            time_diff = abs(frame.time_sec - segment_mid)
            
            if time_diff > max_time_diff:
                issues.append({
                    "segment_id": segment_id,
                    "frame_id": frame_id,
                    "time_diff": time_diff,
                    "segment_time": segment_mid,
                    "frame_time": frame.time_sec
                })
    
    return {
        "valid": len(issues) == 0,
        "issues_count": len(issues),
        "issues": issues
    }


def fill_empty_alignments(
    alignments: List[Dict[str, Any]],
    audio_segments: List[AudioSegment],
    visual_frames: List[VisualKeyframe]
) -> List[Dict[str, Any]]:
    """
    For alignments with no frame_ids, assign the nearest frame based on timing.
    """
    segment_lookup = {s.segment_id: s for s in audio_segments}
    
    for alignment in alignments:
        if not alignment["frame_ids"]:
            segment_id = alignment["segment_id"]
            if segment_id in segment_lookup:
                segment = segment_lookup[segment_id]
                segment_mid = (segment.start_sec + segment.end_sec) / 2
                nearest = find_nearest_frame(segment_mid, visual_frames)
                if nearest:
                    alignment["frame_ids"] = [nearest]
                    print(f"[decoder][INFO] Filled empty alignment for {segment_id} with {nearest}")
    
    return alignments


def align_audio_to_visual(
    audio_segments: List[AudioSegment],
    visual_frames: List[VisualKeyframe],
    tolerance_sec: float = 2.0
) -> List[Dict[str, Any]]:
    """
    For each audio segment, find keyframes whose time lies within
    [start_sec - tolerance, end_sec + tolerance].
    """
    alignments: List[Dict[str, Any]] = []

    for seg in audio_segments:
        frame_ids: List[str] = []
        for frame in visual_frames:
            if (frame.time_sec >= seg.start_sec - tolerance_sec
                and frame.time_sec <= seg.end_sec + tolerance_sec):
                frame_ids.append(frame.frame_id)

        alignments.append({
            "segment_id": seg.segment_id,
            "frame_ids": frame_ids
        })

    return alignments


# ---------------------------------------------------------
# 4) Top-level decoder → video_decode.json
# ---------------------------------------------------------

def decode_video_to_json(
    video_path: str,
    project_id: str,
    output_json_path: str,
    frames_output_dir: str,
    interval_sec: float = 10.0,
    language: Optional[str] = None,
    whisper_model: str = "base",
    ocr_lang: str = "eng"
) -> None:
    """
    Full decode step:
      - transcribe MP4 locally with Whisper
      - sample frames less frequently
      - run OCR on each sampled frame
      - build canonical JSON with:
          video metadata
          audio_segments
          visual_keyframes (with ocr_text)
          audio_to_visual alignments
    """
    
    # Validate input video exists
    if not os.path.exists(video_path):
        raise FileNotFoundError(f"Video file not found: {video_path}")
    
    # Validate video file size
    video_size = os.path.getsize(video_path)
    if video_size == 0:
        raise ValueError(f"Video file is empty: {video_path}")
    
    print(f"[decoder] Processing video: {video_path} ({video_size / (1024*1024):.2f} MB)")
    
    # Validate interval
    if interval_sec <= 0:
        raise ValueError(f"interval_sec must be positive, got {interval_sec}")

    # 1. Transcribe
    audio_segments = transcribe_video_local(
        video_path=video_path,
        model_name=whisper_model,
        language=language
    )
    
    # Validate transcription produced results
    if not audio_segments:
        print("[decoder][WARN] No audio segments detected. Video may be silent or corrupted.")
    
    # 2. Visual frames + OCR
    visual_keyframes, duration_sec, fps, width, height = extract_keyframes_fixed_interval(
        video_path=video_path,
        output_dir=frames_output_dir,
        interval_sec=interval_sec,
        ocr_lang=ocr_lang
    )
    
    # Validate frames were extracted
    if not visual_keyframes:
        raise RuntimeError("Failed to extract any visual keyframes from video")
    
    if duration_sec <= 0:
        raise ValueError(f"Invalid video duration: {duration_sec}")
    
    print(f"[decoder] Video info: {duration_sec:.1f}s @ {fps:.1f} fps, {width}x{height}")

    # 3. Align
    audio_to_visual = align_audio_to_visual(audio_segments, visual_keyframes)
    
    # 3.1 Fix empty alignments
    audio_to_visual = fill_empty_alignments(audio_to_visual, audio_segments, visual_keyframes)
    
    # 3.2 Validate alignments
    validation_report = validate_alignment(audio_to_visual, audio_segments, visual_keyframes)
    if not validation_report["valid"]:
        print(f"[decoder][WARN] Found {validation_report['issues_count']} suspicious alignments")
        for issue in validation_report["issues"][:5]:  # Show first 5
            print(f"  - {issue['segment_id']} ↔ {issue['frame_id']}: time_diff={issue['time_diff']:.1f}s")
    else:
        print(f"[decoder][OK] All alignments validated successfully")

    # 4. Build JSON
    video_decode = {
        "schema_version": "1.0",
        "project_id": project_id,
        "created_at": now_iso(),
        "video": {
            "video_id": "vid_0001",
            "path": os.path.abspath(video_path),
            "duration_sec": float(duration_sec),
            "frame_rate_fps": float(fps),
            "resolution": {
                "width": width,
                "height": height
            },
            "metadata": {}
        },
        "models": {
            "asr": {
                "name": whisper_model,
                "provider": "local_whisper",
                "language": language or "auto"
            },
            "vision": {
                "name": "none",
                "provider": "none",
                "notes": "Caption model not implemented yet"
            },
            "ocr": {
                "name": "tesseract",
                "provider": "local_tesseract",
                "notes": f"pytesseract with lang={ocr_lang}"
            }
        },
        "audio_segments": [asdict(seg) for seg in audio_segments],
        "visual_keyframes": [asdict(frame) for frame in visual_keyframes],
        "alignments": {
            "audio_to_visual": audio_to_visual
        },
        "metadata": {
            "frame_sampling_strategy": "fixed_interval",
            "frame_sampling_interval_sec": interval_sec,
            "alignment_validation": validation_report,
            "notes": "Base decoded representation. All downstream steps must read from this file."
        }
    }

    # 5. Save JSON
    # Ensure parent directory exists
    os.makedirs(os.path.dirname(output_json_path), exist_ok=True)
    with open(output_json_path, "w", encoding="utf-8") as f:
        json.dump(video_decode, f, ensure_ascii=False, indent=2)

    print(f"[decoder] Saved JSON to: {os.path.abspath(output_json_path)}")
    print(f"[decoder] Frames directory: {os.path.abspath(frames_output_dir)}")


# =========================================================
# SCRIPT EXECUTION
# =========================================================

def main():
    """
    Main function to be called by the pipeline orchestrator.
    Paths are now relative to the workspace.
    """
    # --- PATHS CHANGED FOR API ---
    INPUT_VIDEO = "workspace/input_video.mp4"
    PROJECT_ID = "video_project"
    OUTPUT_JSON = "workspace/decoded_video.json"
    FRAMES_DIR = "workspace/frames"
    # --- END OF CHANGES ---

    decode_video_to_json(
        video_path=INPUT_VIDEO,
        project_id=PROJECT_ID,
        output_json_path=OUTPUT_JSON,
        frames_output_dir=FRAMES_DIR,
        interval_sec=10.0,
        language="en",
        whisper_model="base",
        ocr_lang="eng"
    )

if __name__ == "__main__":
    # This block allows the script to be run directly
    # e.g., `python video_decoder.py`
    # It will NOT run when imported by `run_pipeline.py`
    main()